# Generated by Django 4.2.4 on 2023-08-31 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(max_length=100, verbose_name='№ документу')),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Дата додавання')),
                ('reg_date', models.CharField(max_length=10, verbose_name='Дата документу')),
                ('doc_type', models.CharField(max_length=100, verbose_name='Тип документу')),
                ('rp_number', models.CharField(max_length=100, verbose_name='№ РП ЛЗ')),
                ('drug_name', models.TextField(max_length=1000, verbose_name='Назва ЛЗ, форма випуску')),
                ('serial_num', models.CharField(max_length=100, verbose_name='Серія №')),
                ('manufacture', models.CharField(max_length=255, verbose_name='Назва виробника, країна')),
            ],
        ),
    ]
